### PR TITLE
PR addressing issue #10

### PR DESCRIPTION
**Pull request by tullo**
This PR addresses some of the issues pointed out by google pagespeed

### CODE REVIEW

**Comment by mraible** [comment]
Thanks! I cloned this branch and ran some quick tests on it. I found that when the page loaded, I saw the following JS error in my console.

```
Uncaught ReferenceError: $ is not defined
```

**Comment by mraible** [comment]
I figured out a way to fix this. See changes at https://gist.github.com/mraible/ab23fc9ea1412acae74f.

**Comment by tullo** [comment]
That fix works for me as well. No JS errors in my console.
Update: The removal of material.init() from index.html breaks the UI - e.g. checkboxes.

The exception at page load does not seem to harm things as everything works as expected.

**Comment by mraible** [comment]
I found that removing arrive.js solved the checkbox issue.

**Pull request merged**
